### PR TITLE
Feature/mapping for mongodb odm

### PR DESCRIPTION
**Pull request by fabiocarneiro**
support mapping for mongodb

### CODE REVIEW

**Comment by danizord** [comment]
Can't move configs to `module.config.php`?

**Comment by danizord** [comment]
Needs rebase

**Comment by prolic** [comment]
What's the status?

**Comment by prolic** [comment]
MongoDB Mapping needs isEmbeddedDocument = true instead of isEmbeddedClass = true.

**Comment by prolic** [comment]
See also: https://github.com/zfbrasil/doctrine-money-module/pull/20

**Comment by prolic** [comment]
This PR can get closed, see https://github.com/zfbrasil/doctrine-money-module/pull/20 instead.

**Pull request closed without merging**
